### ISSUE TITLE
IndexError when trying to install model from example code

### ISSUE THREAD

**Issue by raffieeey** [huseinzol05/malaya#91]
When trying this code, everything is okay.

`>>> model = malaya.sentiment.multinomial()`

I'm experiencing this error when trying this code. I've tried xlnet, tiny-bert etc. still the same error

```
>>> model = malaya.sentiment.transformer(model = 'tiny-albert')

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1139, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1192, in InternalParse
    (data, new_pos) = decoder._DecodeUnknownField(
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 989, in _DecodeUnknownField
    (data, pos) = _DecodeUnknownFieldSet(buffer, pos)
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 963, in _DecodeUnknownFieldSet
    (tag_bytes, pos) = ReadTag(buffer, pos)
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 192, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
IndexError: index out of bounds on dimension 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\malaya\function\__init__.py", line 145, in load_graph
    graph_def.ParseFromString(f.read())
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\herpetologist\__init__.py", line 100, in check
    return func(*args, **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\malaya\sentiment.py", line 112, in transformer
    return softmax.transformer(
  File "C:\Users\user\anaconda3\lib\site-packages\malaya\supervised\softmax.py", line 78, in transformer
    g = load_graph(path['model'], **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\malaya\function\__init__.py", line 147, in load_graph
    path = frozen_graph_filename.split('Malaya/')[1]
IndexError: list index out of range
```

**Comment by huseinzol05** [comment]
I just released 4.4,

Can you try install it,

```bash
pip install malaya==4.4
pip install malaya-boilerplate -U
```

**Comment by raffieeey** [comment]
Tested your solution, and got below error

```

>>> model = malaya.sentiment.transformer(model = 'tiny-albert')
downloading frozen model to C:\Users\user\Malaya\sentiment\tiny-albert\model.pb
1.00MB [00:00, 250MB/s]
downloading frozen vocab to C:\Users\user\Malaya\sentiment\tiny-albert\sp10m.cased.v10.vocab
184%|███████████████████████████████████████████████████████████████████████████████| 1.00/0.54 [00:01<00:00, 1.74s/MB]
downloading frozen tokenizer to C:\Users\user\Malaya\sentiment\tiny-albert\sp10m.cased.v10.model
135%|███████████████████████████████████████████████████████████████████████████████| 1.00/0.74 [00:01<00:00, 1.22s/MB]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1139, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1192, in InternalParse
    (data, new_pos) = decoder._DecodeUnknownField(
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 989, in _DecodeUnknownField
    (data, pos) = _DecodeUnknownFieldSet(buffer, pos)
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 963, in _DecodeUnknownFieldSet
    (tag_bytes, pos) = ReadTag(buffer, pos)
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 192, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
IndexError: index out of bounds on dimension 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\malaya_boilerplate\frozen_graph.py", line 260, in load_graph
    graph_def.ParseFromString(f.read())
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\herpetologist\__init__.py", line 100, in check
    return func(*args, **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\malaya\sentiment.py", line 112, in transformer
    return softmax.transformer(
  File "C:\Users\user\anaconda3\lib\site-packages\malaya\supervised\softmax.py", line 80, in transformer
    g = load_graph(path['model'], **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\malaya_boilerplate\frozen_graph.py", line 262, in load_graph
    raise Exception(
Exception: Truncated message., file corrupted due to some reasons, please run `malaya.utils.delete_cache('sentiment\tiny-albert')` and try again


```
Ran this code

```
>>> malaya.utils.delete_cache('sentiment/xlnet')
True
>>> malaya.utils.delete_cache('sentiment/tiny-albert')
True
```

Still the same error

```

>>> model = malaya.sentiment.transformer(model = 'tiny-albert')
downloading frozen model to C:\Users\user\Malaya\sentiment\tiny-albert\model.pb
1.00MB [00:00, 250MB/s]
downloading frozen vocab to C:\Users\user\Malaya\sentiment\tiny-albert\sp10m.cased.v10.vocab
184%|███████████████████████████████████████████████████████████████████████████████| 1.00/0.54 [00:01<00:00, 1.74s/MB]
downloading frozen tokenizer to C:\Users\user\Malaya\sentiment\tiny-albert\sp10m.cased.v10.model
135%|███████████████████████████████████████████████████████████████████████████████| 1.00/0.74 [00:01<00:00, 1.22s/MB]
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1139, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1192, in InternalParse
    (data, new_pos) = decoder._DecodeUnknownField(
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 989, in _DecodeUnknownField
    (data, pos) = _DecodeUnknownFieldSet(buffer, pos)
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 963, in _DecodeUnknownFieldSet
    (tag_bytes, pos) = ReadTag(buffer, pos)
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 192, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
IndexError: index out of bounds on dimension 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\malaya_boilerplate\frozen_graph.py", line 260, in load_graph
    graph_def.ParseFromString(f.read())
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "C:\Users\user\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\herpetologist\__init__.py", line 100, in check
    return func(*args, **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\malaya\sentiment.py", line 112, in transformer
    return softmax.transformer(
  File "C:\Users\user\anaconda3\lib\site-packages\malaya\supervised\softmax.py", line 80, in transformer
    g = load_graph(path['model'], **kwargs)
  File "C:\Users\user\anaconda3\lib\site-packages\malaya_boilerplate\frozen_graph.py", line 262, in load_graph
    raise Exception(
Exception: Truncated message., file corrupted due to some reasons, please run `malaya.utils.delete_cache('sentiment\tiny-albert')` and try again


```

**Comment by raffieeey** [comment]
Just to add, the transformer for translating EN to MS also having IndexError problem

>> transformer = malaya.translation.en_ms.transformer()

```
downloading frozen model to C:\Users\user\Malaya\translation-en-ms\base\model.pb
1.00MB [00:00, 167MB/s]                    
downloading frozen vocab to C:\Users\user\Malaya\translation-en-ms\base\en-ms.subwords
1.00MB [00:00, 1.64MB/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in MergeFromString(self, serialized)
   1138     try:
-> 1139       if self._InternalParse(serialized, 0, length) != length:
   1140         # The only reason _InternalParse would return early is if it

~\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in InternalParse(self, buffer, pos, end)
   1191         old_pos = new_pos
-> 1192         (data, new_pos) = decoder._DecodeUnknownField(
   1193             buffer, new_pos, wire_type)  # pylint: disable=protected-access

~\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in _DecodeUnknownField(buffer, pos, wire_type)
    988   elif wire_type == wire_format.WIRETYPE_START_GROUP:
--> 989     (data, pos) = _DecodeUnknownFieldSet(buffer, pos)
    990   elif wire_type == wire_format.WIRETYPE_END_GROUP:

~\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in _DecodeUnknownFieldSet(buffer, pos, end_pos)
    962   while end_pos is None or pos < end_pos:
--> 963     (tag_bytes, pos) = ReadTag(buffer, pos)
    964     (tag, _) = _DecodeVarint(tag_bytes, 0)

~\anaconda3\lib\site-packages\google\protobuf\internal\decoder.py in ReadTag(buffer, pos)
    191   start = pos
--> 192   while six.indexbytes(buffer, pos) & 0x80:
    193     pos += 1

IndexError: index out of bounds on dimension 1

During handling of the above exception, another exception occurred:

DecodeError                               Traceback (most recent call last)
~\anaconda3\lib\site-packages\malaya\function\__init__.py in load_graph(frozen_graph_filename, **kwargs)

~\anaconda3\lib\site-packages\google\protobuf\message.py in ParseFromString(self, serialized)
    198     self.Clear()
--> 199     return self.MergeFromString(serialized)
    200 

~\anaconda3\lib\site-packages\google\protobuf\internal\python_message.py in MergeFromString(self, serialized)
   1144       # Now ord(buf[p:p+1]) == ord('') gets TypeError.
-> 1145       raise message_mod.DecodeError('Truncated message.')
   1146     except struct.error as e:

DecodeError: Truncated message.

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
<ipython-input-13-ad1528f8bc4d> in <module>
----> 1 transformer = malaya.translation.en_ms.transformer()

~\AppData\Roaming\Python\Python38\site-packages\herpetologist\__init__.py in check(*args, **kwargs)
     98                 nested_check(v, p)
     99 
--> 100         return func(*args, **kwargs)
    101 
    102     return check

~\anaconda3\lib\site-packages\malaya\translation\en_ms.py in transformer(model, quantized, **kwargs)
     95 
     96     else:
---> 97         return load_transformer.load(
     98             module='translation-en-ms',
     99             model=model,

~\anaconda3\lib\site-packages\malaya\supervised\transformer.py in load(module, model, encoder, model_class, quantized, **kwargs)
     49     path = check_file(
     50         file=model,
---> 51         module=module,
     52         keys={'model': 'model.pb', 'vocab': LM_VOCAB[module]},
     53         quantized=quantized,

~\anaconda3\lib\site-packages\malaya\function\__init__.py in load_graph(frozen_graph_filename, **kwargs)

IndexError: list index out of range
```

**Comment by huseinzol05** [comment]
What is your tensorflow version?

**Comment by raffieeey** [comment]
My python  version is
```
(base) C:\Users\user>python
Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
```

My tf is 2.5.0
```
>>> import tensorflow as tf
>>> print(tf.__version__)
2.5.0
```

**Comment by huseinzol05** [comment]
Can you try TF version <= 2.4, I tested the code on TF 1.15.4 and 2.4.1

**Comment by raffieeey** [comment]
Hi, I've tried using 2 PCs and 1 Macbook (All using TF 2.4.1). All produce the same error. I even reinstall anaconda just to make it work, not sure what seems to be broken. Is it because I dont have CUDA install?

**Comment by huseinzol05** [comment]
I tried on colab, no problem using TF 2.5, https://colab.research.google.com/drive/1HTUkq35Adz63n75s-r67abdI1fnt7avL?usp=sharing

**Comment by huseinzol05** [comment]
can u try using pip install?

**Comment by raffieeey** [comment]
Yeah I'm using pip to install malaya and tf, is it possible that this problem happen to windows os? i.e.

 `malaya.utils.delete_cache('sentiment\tiny-albert')` 

I have to change to 

 `malaya.utils.delete_cache('sentiment/tiny-albert')` 

Notice the "\" to "/" to get the cache to be cleaned. Hence, when downloading the model we get the indexerror because

`frozen_graph_filename.split('Malaya/')[1]`

which should be 
`
frozen_graph_filename.split('Malaya\')[1]`

for Windows?

**Comment by ernyigoh** [comment]
encounter the same problem too 

`Exception: Truncated message., file corrupted due to some reasons, please run `malaya.utils.delete_cache('sentiment\tiny-albert')` and try again`

**Comment by huseinzol05** [comment]
Herm, this issue seems only happened on Windows, let me try to Docker Windows and try it.

**Comment by huseinzol05** [comment]
Fixed, make sure install latest `malaya-boilerplate`,

```
pip install malaya-boilerplate -U
```

And retry again,

```python
import malaya
model = malaya.emotion.transformer(model = 'albert')
anger_text = 'babi la company ni, aku dah la penat datang dari jauh' 
model.predict([anger_text])
```

My OS, Windows 10, Python 3.7, Tensorflow 2.5.
